# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: Microsite Void
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/verify_microsite.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest

    name: Microsite
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - run: echo NOOP
